### ISSUE TITLE
Mobile Pages

### ISSUE THREAD

**Issue by rguarascia** [AndroidScout/AndroidScout.github.io#10]
Viewing on mobile will show the text tab in the selection when viewing the first one. Like the attached photo.
![photo_2016-01-16_16-36-59](https://cloud.githubusercontent.com/assets/6396340/12374636/8bcb096e-bc6f-11e5-8e6e-ae36104bffdb.jpg)

**Comment by emachlev** [comment]
Fixed with the new design. Closing issue.
