### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by rguarascia** [AndroidScout/AndroidScout.github.io#9]
The newest pushes has broken the ability to scroll down the page.
![screen shot 2016-01-16 at 4 34 50 pm](https://cloud.githubusercontent.com/assets/6396340/12374626/163e9c9c-bc6f-11e5-9561-a04fd942dd4c.png)

**Comment by emachlev** [comment]
The .contain division is blocked by the bar on top and can't stretch itself to fill the page. You can tell by the scroll bar on the right when visiting from a Windows machine: 

![capture](https://cloud.githubusercontent.com/assets/5901035/12374694/47866bbc-bcac-11e5-8fba-2e03fa400e94.PNG)

It looks like there's an easy way to solve this. I'll take a look.

**Comment by emachlev** [comment]
Fixed with the new design. Closing issue.
